Repository appsolve-solux/wearther_backend, pull requests merged in 2025-01, with the labels that each got.

#7 API 공통응답과 에러 핸들러
  build.gradle
  src/main/java/com/appsolve/wearther_backend/apiResponse/ApiResponse.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/dto/ExceptionDto.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/CustomException.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/ErrorCode.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/handler/GlobalExceptionHandler.java
Labels: feat

#5 [INIT] 초기 데이터 세팅
  src/main/java/com/appsolve/wearther_backend/init_data/InitService.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/LowerWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/OtherWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/Taste.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/TasteLowerWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/TasteOtherWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/TasteUpperWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/UpperWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/Weather.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/WeatherLowerWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/WeatherOtherWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/WeatherUpperWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/LowerWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/OtherWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/TasteLowerWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/TasteOtherWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/TasteRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/TasteUpperWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/UpperWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/WeatherLowerWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/WeatherOtherWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/WeatherRepostory.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/WeatherUpperWearRepository.java
Labels: feat, 연재🍀

#2 [FEAT] 위치 관련 api
  src/main/java/com/appsolve/wearther_backend/Controller/LocationController.java
  src/main/java/com/appsolve/wearther_backend/Dto/LocationIndexUpdateRequestDto.java
  src/main/java/com/appsolve/wearther_backend/Dto/LocationPostRequestDto.java
  src/main/java/com/appsolve/wearther_backend/Entity/LocationEntity.java
  src/main/java/com/appsolve/wearther_backend/Repository/LocationRepository.java
  src/main/java/com/appsolve/wearther_backend/Service/LocationService.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/ErrorCode.java
Labels: feat, 서연🍀

#11 [FEAT] 체질 관련 api 추가
  src/main/java/com/appsolve/wearther_backend/Controller/MemberController.java
  src/main/java/com/appsolve/wearther_backend/Entity/MemberEntity.java
  src/main/java/com/appsolve/wearther_backend/Repository/MemberRepository.java
  src/main/java/com/appsolve/wearther_backend/Service/MemberService.java
Labels: feat, 서연🍀

#13 [FEAT] 내 옷장 조회 및 추천 상품 조회
  src/main/java/com/appsolve/wearther_backend/Entity/MemberEntity.java
  src/main/java/com/appsolve/wearther_backend/Entity/MemberTaste.java
  src/main/java/com/appsolve/wearther_backend/Repository/MemberRepository.java
  src/main/java/com/appsolve/wearther_backend/Repository/MemberTasteRepository.java
  src/main/java/com/appsolve/wearther_backend/Service/MemberService.java
  src/main/java/com/appsolve/wearther_backend/Service/TasteService.java
  src/main/java/com/appsolve/wearther_backend/closet/api/ClosetController.java
  src/main/java/com/appsolve/wearther_backend/closet/dto/BuyRecommendDto.java
  src/main/java/com/appsolve/wearther_backend/closet/dto/ClosetResponseDto.java
  src/main/java/com/appsolve/wearther_backend/closet/entity/Closet.java
  src/main/java/com/appsolve/wearther_backend/closet/entity/ClosetLower.java
  src/main/java/com/appsolve/wearther_backend/closet/entity/ClosetOther.java
  src/main/java/com/appsolve/wearther_backend/closet/entity/ClosetUpper.java
  src/main/java/com/appsolve/wearther_backend/closet/repository/ClosetLowerRepository.java
  src/main/java/com/appsolve/wearther_backend/closet/repository/ClosetOtherRepository.java
  src/main/java/com/appsolve/wearther_backend/closet/repository/ClosetRepository.java
  src/main/java/com/appsolve/wearther_backend/closet/repository/ClosetUpperRepository.java
  src/main/java/com/appsolve/wearther_backend/closet/service/ClosetService.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/LowerWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/OtherWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/UpperWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/TasteLowerWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/TasteOtherWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/TasteUpperWearRepository.java
Labels: feat, 연재🍀

#16 [FEAT] 취향 조회 및 변경
  src/main/java/com/appsolve/wearther_backend/Controller/LocationController.java
  src/main/java/com/appsolve/wearther_backend/Controller/MemberTasteController.java
  src/main/java/com/appsolve/wearther_backend/Entity/Location.java
  src/main/java/com/appsolve/wearther_backend/Entity/MemberTaste.java
  src/main/java/com/appsolve/wearther_backend/Repository/LocationRepository.java
  src/main/java/com/appsolve/wearther_backend/Repository/MemberRepository.java
  src/main/java/com/appsolve/wearther_backend/Repository/MemberTasteRepository.java
  src/main/java/com/appsolve/wearther_backend/Service/LocationService.java
  src/main/java/com/appsolve/wearther_backend/Service/MemberTasteService.java
Labels: feat, 서연🍀

#18 [FEAT] 사용자 보유 옷 수정
  src/main/java/com/appsolve/wearther_backend/closet/api/ClosetController.java
  src/main/java/com/appsolve/wearther_backend/closet/dto/ClosetUpdateRequestDto.java
  src/main/java/com/appsolve/wearther_backend/closet/entity/Closet.java
  src/main/java/com/appsolve/wearther_backend/closet/entity/ClosetUpper.java
  src/main/java/com/appsolve/wearther_backend/closet/repository/ClosetLowerRepository.java
  src/main/java/com/appsolve/wearther_backend/closet/repository/ClosetOtherRepository.java
  src/main/java/com/appsolve/wearther_backend/closet/repository/ClosetUpperRepository.java
  src/main/java/com/appsolve/wearther_backend/closet/service/ClosetService.java
Labels: feat, 서연🍀

#24 [FEAT] 프로필 편집 조회
  src/main/java/com/appsolve/wearther_backend/profileEdit/ProfileEditController.java
  src/main/java/com/appsolve/wearther_backend/profileEdit/ProfileEditResponseDto.java
  src/main/java/com/appsolve/wearther_backend/profileEdit/ProfileEditService.java
Labels: feat, 서연🍀

#26 [FEAT] 즐겨찾기 들어갔을 때 보이는 내용
  src/main/java/com/appsolve/wearther_backend/Controller/LocationController.java
  src/main/java/com/appsolve/wearther_backend/Dto/LocationPostRequestDto.java
  src/main/java/com/appsolve/wearther_backend/Dto/LocationWeatherResponseDto.java
  src/main/java/com/appsolve/wearther_backend/Entity/Location.java
  src/main/java/com/appsolve/wearther_backend/Repository/LocationRepository.java
  src/main/java/com/appsolve/wearther_backend/Service/LocationConverter.java
  src/main/java/com/appsolve/wearther_backend/Service/LocationService.java
  src/main/java/com/appsolve/wearther_backend/Service/LocationWeatherService.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/ErrorCode.java
Labels: feat, 서연🍀

#27 [Feat] 회원가입 및 로그인
  .gitignore
  build.gradle
  src/main/java/com/appsolve/wearther_backend/Controller/MemberController.java
  src/main/java/com/appsolve/wearther_backend/Dto/SignInRequest.java
  src/main/java/com/appsolve/wearther_backend/Dto/SignUpRequest.java
  src/main/java/com/appsolve/wearther_backend/Entity/MemberEntity.java
  src/main/java/com/appsolve/wearther_backend/Repository/MemberRepository.java
  src/main/java/com/appsolve/wearther_backend/Service/MemberService.java
  src/main/java/com/appsolve/wearther_backend/WeartherBackendApplication.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/ApiResponse.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/ErrorCode.java
  src/main/java/com/appsolve/wearther_backend/config/SecurityConfig.java
  src/main/java/com/appsolve/wearther_backend/config/SwaggerConfig.java
  src/main/java/com/appsolve/wearther_backend/config/auth/PrincipalDetails.java
  src/main/java/com/appsolve/wearther_backend/config/auth/PrincipalDetailsService.java
  src/main/java/com/appsolve/wearther_backend/config/jwt/JwtAuthorizationFilter.java
  src/main/java/com/appsolve/wearther_backend/config/jwt/JwtProvider.java
  src/test/java/com/appsolve/wearther_backend/Service/MemberServiceTest.java
Labels: feat, 선희🍀

#29 [FEAT] 현재 위치에 대한 현재 온도 반환
  src/main/java/com/appsolve/wearther_backend/Controller/LocationController.java
  src/main/java/com/appsolve/wearther_backend/Service/LocationWeatherService.java
Labels: feat, 서연🍀

#30 [FEAT] 구매 링크 제공 기능 구현
  src/main/java/com/appsolve/wearther_backend/closet/ShoppingUrls.java
  src/main/java/com/appsolve/wearther_backend/closet/api/ClosetController.java
  src/main/java/com/appsolve/wearther_backend/closet/dto/ShoppingListDto.java
  src/main/java/com/appsolve/wearther_backend/closet/dto/ShoppingRecommendDto.java
  src/main/java/com/appsolve/wearther_backend/closet/service/ClosetService.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/LowerWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/OtherWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/UpperWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/service/LowerWearService.java
  src/main/java/com/appsolve/wearther_backend/init_data/service/OtherWearService.java
  src/main/java/com/appsolve/wearther_backend/init_data/service/UpperWearService.java
Labels: feat, 연재🍀

#33 [FEAT] 회원가입시 옷장, 취향 초기 등록기능
  src/main/java/com/appsolve/wearther_backend/Controller/MemberTasteController.java
  src/main/java/com/appsolve/wearther_backend/Entity/MemberEntity.java
  src/main/java/com/appsolve/wearther_backend/Service/AuthService.java
  src/main/java/com/appsolve/wearther_backend/Service/MemberService.java
  src/main/java/com/appsolve/wearther_backend/Service/MemberTasteService.java
  src/main/java/com/appsolve/wearther_backend/closet/api/ClosetController.java
  src/main/java/com/appsolve/wearther_backend/closet/dto/ClosetUpdateRequestDto.java
  src/main/java/com/appsolve/wearther_backend/closet/entity/Closet.java
  src/main/java/com/appsolve/wearther_backend/closet/service/ClosetService.java
  src/main/java/com/appsolve/wearther_backend/config/jwt/JwtAuthorizationFilter.java
Labels: feat, 선희🍀

#37 [Feat] 홈화면 날씨 기능
  src/main/java/com/appsolve/wearther_backend/home/controller/HomeWeatherController.java
  src/main/java/com/appsolve/wearther_backend/home/dto/WeatherResponseDto.java
  src/main/java/com/appsolve/wearther_backend/home/service/HomeWeatherService.java
Labels: feat, 정우🍀

#39 [FEAT]스프링시큐리티 에러처리
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/ErrorCode.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/handler/JwtExceptionFilter.java
  src/main/java/com/appsolve/wearther_backend/config/SecurityConfig.java
  src/main/java/com/appsolve/wearther_backend/config/jwt/JwtAuthorizationFilter.java
  src/main/java/com/appsolve/wearther_backend/config/jwt/JwtProvider.java
Labels: feat, 선희🍀

#40 [FEAT] 옷장 관련 코드 리팩토링 및 로직 추가
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/ErrorCode.java
  src/main/java/com/appsolve/wearther_backend/closet/api/ClosetController.java
  src/main/java/com/appsolve/wearther_backend/closet/service/ClosetService.java
Labels: feat, 연재🍀, refactor

#44 [FEAT] 오늘의 추천템 기능
  src/main/java/com/appsolve/wearther_backend/apiResponse/exception/ErrorCode.java
  src/main/java/com/appsolve/wearther_backend/home/controller/HomeController.java
  src/main/java/com/appsolve/wearther_backend/home/dto/RecommendResponseDto.java
  src/main/java/com/appsolve/wearther_backend/home/dto/WeatherResponseDto.java
  src/main/java/com/appsolve/wearther_backend/home/service/HomeWeatherService.java
  src/main/java/com/appsolve/wearther_backend/home/service/TodayRecommendService.java
  src/main/java/com/appsolve/wearther_backend/home/service/UvService.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/LocationInfo.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/WeatherLowerWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/WeatherOtherWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/WeatherUpperWear.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/LocationInfoRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/WeatherLowerWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/WeatherOtherWearRepository.java
  src/main/java/com/appsolve/wearther_backend/init_data/repository/WeatherUpperWearRepository.java
Labels: feat, 정우🍀

#47 [REFACTOR] 담당 api 토큰 이용하도록 수정
  src/main/java/com/appsolve/wearther_backend/Controller/LocationController.java
  src/main/java/com/appsolve/wearther_backend/Controller/MemberController.java
  src/main/java/com/appsolve/wearther_backend/Controller/MemberTasteController.java
  src/main/java/com/appsolve/wearther_backend/Dto/LocationIndexUpdateRequestDto.java
  src/main/java/com/appsolve/wearther_backend/Dto/LocationPostRequestDto.java
  src/main/java/com/appsolve/wearther_backend/Service/LocationService.java
  src/main/java/com/appsolve/wearther_backend/Service/MemberService.java
  src/main/java/com/appsolve/wearther_backend/closet/api/ClosetController.java
  src/main/java/com/appsolve/wearther_backend/profileEdit/ProfileEditController.java
Labels: 서연🍀, refactor

#49 [REFACTOR] 토큰에서 멤버 아이디 받게 수정 + 피드백 반영
  src/main/java/com/appsolve/wearther_backend/home/controller/HomeController.java
  src/main/java/com/appsolve/wearther_backend/home/service/HomeWeatherService.java
  src/main/java/com/appsolve/wearther_backend/home/service/TodayRecommendService.java
  src/main/java/com/appsolve/wearther_backend/home/service/UvService.java
  src/main/java/com/appsolve/wearther_backend/init_data/entity/LocationInfo.java
Labels: 정우🍀, refactor
